# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
  - stage: BuildDev
    displayName: Build for dev
    jobs:
      - job: BuildMobileApp
        displayName: Build App for Mobile
      - job: BuildReactApp
        displayName: Build App for React
      - job: BuildNodeApp
        displayName: Build App for Node
  - stage: BuildStaging
    displayName: Build for staging
    jobs:
      - job: BuildMobileApp
        displayName: Build App for Mobile
      - job: BuildReactApp
        displayName: Build App for React
      - job: BuildNodeApp
        displayName: Build App for Node
  - stage: BuildProd
    displayName: Build for prod
    jobs:
      - job: BuildMobileApp
        displayName: Build App for Mobile
      - job: BuildReactApp
        displayName: Build App for React
      - job: BuildNodeApp
        displayName: Build App for Node
