trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
  - stage: BuildDev
    displayName: Build for dev
    jobs:
      - job: BuildMobileApp
        displayName: Build App for Mobile
        steps:
          - script: echo Building Mobile application
            displayName: Build mobile app
      - job: BuildReactApp
        dependsOn: BuildMobileApp
        displayName: Build App for React
        steps:
          - script: echo Building react application
            displayName: Build react app
      - job: BuildNodeApp
        dependsOn: BuildReactApp
        displayName: Build App for Node
        steps:
          - script: echo node application
            displayName: Build node app
          
  - stage: BuildStaging
    displayName: Build for staging
    dependsOn: BuildDev
    condition: succeeded('BuildDev')
    jobs:
      - job: BuildMobileApp
        displayName: Build App for Mobile
        steps:
          - script: echo Building Mobile application
            displayName: Build mobile app
      - job: BuildReactApp
        dependsOn: BuildMobileApp
        displayName: Build App for React
        steps:
          - script: echo Building react application
            displayName: Build react app
      - job: BuildNodeApp
        dependsOn: BuildReactApp
        displayName: Build App for Node
        steps:
          - script: echo node application
            displayName: Build node ap

  - stage: BuildProd
    displayName: Build for prod
    dependsOn:
    - BuildDev
    - BuildStaging
    condition: and(succeeded('BuildDev'), succeeded('BuildStaging'))
    jobs:
      - job: BuildMobileApp
        displayName: Build App for Mobile
        steps:
          - script: echo Building Mobile application
            displayName: Build mobile app
      - job: BuildReactApp
        dependsOn: BuildMobileApp
        displayName: Build App for React
        steps:
          - script: echo Building react application
            displayName: Build react app
      - job: BuildNodeApp
        dependsOn: BuildReactApp
        displayName: Build App for Node
        steps:
          - script: echo node application
            displayName: Build node ap
